# Generated by Django 5.1.2 on 2024-10-14 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lbms_app', '0002_book_bookissue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookissue',
            old_name='student',
            new_name='reader',
        ),
    ]
